https://github.com/canonical/cloud-init/commit/2730521fd566f855863c5ed049a1df26abcd0770

=== Begin SRU Template ===
[Impact]
When using DataSourceRbxCloud, cloud-init could wrongly raise an exception
when the metadata disk could not be found. This commit fixes that.


[Test Case]

There is an upstream test for this bug:
https://github.com/canonical/cloud-init/blob/master/tests/integration_tests/bugs/test_gh632.py

=== Xenial ===
============================= test session starts ==============================
platform linux -- Python 3.5.9, pytest-5.4.2, py-1.8.1, pluggy-0.13.1
rootdir: /home/james/cloud-init, inifile: tox.ini
plugins: cov-2.9.0
collected 1 item

tests/integration_tests/bugs/test_gh632.py Detected image: image_id=xenial os=ubuntu release=xenial
Detected image: image_id=xenial os=ubuntu release=xenial
Settings:
CLOUD_INIT_SOURCE=PROPOSED
COLLECT_LOGS=NEVER
EXISTING_INSTANCE_ID=None
GCE_PROJECT=ubuntu-server-277015
GCE_REGION=us-central1
GCE_ZONE=a
INSTANCE_TYPE=None
KEEP_IMAGE=False
KEEP_INSTANCE=False
LOCAL_LOG_PATH=/tmp/cloud_init_test_logs
OCI_COMPARTMENT_ID=ocid1.compartment.oc1..aaaaaaaanz4b63fdemmuag77dg2pi22xfyhrpq46hcgdd3dozkvqfzwwjwxa
OS_IMAGE=xenial
PLATFORM=lxd_container
RUN_UNSTABLE=False
Setting up environment for lxd_container
Launching instance with launch_kwargs:
user_data=None
image_id=ubuntu:de03ec8f36f75815b6b6c6dcae2dc0c7b09079b035a27c46ff854b0977f9139b
wait=False
['lxc', 'init', 'ubuntu:de03ec8f36f75815b6b6c6dcae2dc0c7b09079b035a27c46ff854b0977f9139b']
Launched instance: LXDInstance(name=deciding-bunny)
Installing proposed image
Installed cloud-init version: 20.4-0ubuntu1~16.04.1
Created new image: local:deciding-bunny-snapshot
Done with environment setup
Launching instance with launch_kwargs:
user_data=None
image_id=local:deciding-bunny-snapshot
wait=False
['lxc', 'init', 'local:deciding-bunny-snapshot']
Launched instance: LXDInstance(name=happy-jaguar)
Instance restarted; waiting for boot
.Deleting snapshot image created for this testrun: local:deciding-bunny-snapshot


========================= 1 passed in 99.11s (0:01:39) =========================

=== Bionic ===
============================= test session starts ==============================
platform linux -- Python 3.5.9, pytest-5.4.2, py-1.8.1, pluggy-0.13.1
rootdir: /home/james/cloud-init, inifile: tox.ini
plugins: cov-2.9.0
collected 1 item

tests/integration_tests/bugs/test_gh632.py Detected image: image_id=bionic os=ubuntu release=bionic
Detected image: image_id=bionic os=ubuntu release=bionic
Settings:
CLOUD_INIT_SOURCE=PROPOSED
COLLECT_LOGS=NEVER
EXISTING_INSTANCE_ID=None
GCE_PROJECT=ubuntu-server-277015
GCE_REGION=us-central1
GCE_ZONE=a
INSTANCE_TYPE=None
KEEP_IMAGE=False
KEEP_INSTANCE=False
LOCAL_LOG_PATH=/tmp/cloud_init_test_logs
OCI_COMPARTMENT_ID=ocid1.compartment.oc1..aaaaaaaanz4b63fdemmuag77dg2pi22xfyhrpq46hcgdd3dozkvqfzwwjwxa
OS_IMAGE=bionic
PLATFORM=lxd_container
RUN_UNSTABLE=False
Setting up environment for lxd_container
Launching instance with launch_kwargs:
image_id=ubuntu:95c0e536d361eb5ac953ad343e0342c2f615e4aea714ca8a64126a228b809cae
wait=False
user_data=None
['lxc', 'init', 'ubuntu:95c0e536d361eb5ac953ad343e0342c2f615e4aea714ca8a64126a228b809cae']
Launched instance: LXDInstance(name=in-seal)
Installing proposed image
Installed cloud-init version: 20.4-0ubuntu1~18.04.1
Created new image: local:in-seal-snapshot
Done with environment setup
Launching instance with launch_kwargs:
image_id=local:in-seal-snapshot
wait=False
user_data=None
['lxc', 'init', 'local:in-seal-snapshot']
Launched instance: LXDInstance(name=key-pipefish)
Instance restarted; waiting for boot
.Deleting snapshot image created for this testrun: local:in-seal-snapshot


======================== 1 passed in 109.97s (0:01:49) =========================

=== Focal ===
============================= test session starts ==============================
platform linux -- Python 3.5.9, pytest-5.4.2, py-1.8.1, pluggy-0.13.1
rootdir: /home/james/cloud-init, inifile: tox.ini
plugins: cov-2.9.0
collected 1 item

tests/integration_tests/bugs/test_gh632.py Detected image: image_id=focal os=ubuntu release=focal
Detected image: image_id=focal os=ubuntu release=focal
Settings:
CLOUD_INIT_SOURCE=PROPOSED
COLLECT_LOGS=NEVER
EXISTING_INSTANCE_ID=None
GCE_PROJECT=ubuntu-server-277015
GCE_REGION=us-central1
GCE_ZONE=a
INSTANCE_TYPE=None
KEEP_IMAGE=False
KEEP_INSTANCE=False
LOCAL_LOG_PATH=/tmp/cloud_init_test_logs
OCI_COMPARTMENT_ID=ocid1.compartment.oc1..aaaaaaaanz4b63fdemmuag77dg2pi22xfyhrpq46hcgdd3dozkvqfzwwjwxa
OS_IMAGE=focal
PLATFORM=lxd_container
RUN_UNSTABLE=False
Setting up environment for lxd_container
Launching instance with launch_kwargs:
wait=False
user_data=None
image_id=ubuntu:e0c3495ffd489748aa5151628fa56619e6143958f041223cb4970731ef939cb6
['lxc', 'init', 'ubuntu:e0c3495ffd489748aa5151628fa56619e6143958f041223cb4970731ef939cb6']
Launched instance: LXDInstance(name=good-crappie)
Installing proposed image
Installed cloud-init version: 20.4-0ubuntu1~20.04.1
Created new image: local:good-crappie-snapshot
Done with environment setup
Launching instance with launch_kwargs:
wait=False
user_data=None
image_id=local:good-crappie-snapshot
['lxc', 'init', 'local:good-crappie-snapshot']
Launched instance: LXDInstance(name=sunny-pelican)
Instance restarted; waiting for boot
.Deleting snapshot image created for this testrun: local:good-crappie-snapshot

======================== 1 passed in 120.34s (0:02:00) =========================

=== Groovy ===
============================= test session starts ==============================
platform linux -- Python 3.5.9, pytest-5.4.2, py-1.8.1, pluggy-0.13.1
rootdir: /home/james/cloud-init, inifile: tox.ini
plugins: cov-2.9.0
collected 1 item

tests/integration_tests/bugs/test_gh632.py Detected image: image_id=groovy os=ubuntu release=groovy
Detected image: image_id=groovy os=ubuntu release=groovy
Settings:
CLOUD_INIT_SOURCE=PROPOSED
COLLECT_LOGS=NEVER
EXISTING_INSTANCE_ID=None
GCE_PROJECT=ubuntu-server-277015
GCE_REGION=us-central1
GCE_ZONE=a
INSTANCE_TYPE=None
KEEP_IMAGE=False
KEEP_INSTANCE=False
LOCAL_LOG_PATH=/tmp/cloud_init_test_logs
OCI_COMPARTMENT_ID=ocid1.compartment.oc1..aaaaaaaanz4b63fdemmuag77dg2pi22xfyhrpq46hcgdd3dozkvqfzwwjwxa
OS_IMAGE=groovy
PLATFORM=lxd_container
RUN_UNSTABLE=False
Setting up environment for lxd_container
Launching instance with launch_kwargs:
image_id=ubuntu:bac1692e9ec7f5c5cee35d149ca789121bed238c1182df2134b5aefa3977f3e0
wait=False
user_data=None
['lxc', 'init', 'ubuntu:bac1692e9ec7f5c5cee35d149ca789121bed238c1182df2134b5aefa3977f3e0']
Launched instance: LXDInstance(name=joint-javelin)
Installing proposed image
Installed cloud-init version: 20.4-0ubuntu1~20.10.1
Created new image: local:joint-javelin-snapshot
Done with environment setup
Launching instance with launch_kwargs:
image_id=local:joint-javelin-snapshot
wait=False
user_data=None
['lxc', 'init', 'local:joint-javelin-snapshot']
Launched instance: LXDInstance(name=willing-viper)
Instance restarted; waiting for boot
.Deleting snapshot image created for this testrun: local:joint-javelin-snapshot


======================== 1 passed in 125.46s (0:02:05) =========================

[Regression Potential]
This was unlikely to ever happen in the first place as ds-identify
shouldn't identify DataSourceRbxCloud if there's no metadata disk. Regardless,
the datasource will now be fully processed where it may not have been before.
