https://bugs.launchpad.net/ubuntu/+source/cloud-init/+bug/1898997
http://pad.lv/1898997

=== Begin SRU Template ===
[Impact]

Quoting from the original bug report:

> If we try to deploy a single-NIC machine via MAAS, configuring an Open
> vSwitch bridge as the primary/PXE interface, the machine will install and
> boot Ubuntu 20.04 but it cannot finish the whole configuration (e.g. copying
> of SSH keys) and cannot be accessed/controlled via MAAS. It ends up in a
> "Failed" state.

[Test Case]

There is an upstream integration test case for this bug:
https://github.com/canonical/cloud-init/blob/master/tests/integration_tests/bugs/test_lp1898997.py

This issue does not present on xenial or bionic, so focal and groovy output is
included.

focal:

```
focal inst-nodeps: /tmp/integration-tests-tox/.tmp/package/1/cloud-init-20.4.zip
focal installed: adal==1.2.5,applicationinsights==0.11.9,argcomplete==1.12.2,attrs==20.3.0,azure-cli-core==2.16.0,azure-cli-telemetry==1.0.6,azure-common==1.1.26,azure-core==1.9.0,azure-mgmt-compute==14.0.0,azure-mgmt-core==1.2.1,azure-mgmt-network==13.0.0,azure-mgmt-resource==12.0.0,bcrypt==3.2.0,boto3==1.16.33,botocore==1.19.33,cachetools==4.1.1,certifi==2020.12.5,cffi==1.14.4,chardet==3.0.4,cloud-init @ file:///tmp/integration-tests-tox/.tmp/package/1/cloud-init-20.4.zip,colorama==0.4.4,configobj==5.0.6,configparser==4.0.2,coverage==5.3,cryptography==3.2.1,google-api-core==1.23.0,google-api-python-client==1.12.8,google-auth==1.23.0,google-auth-httplib2==0.0.4,googleapis-common-protos==1.52.0,httplib2==0.18.1,httpretty==1.0.3,humanfriendly==8.2,idna==2.10,iniconfig==1.1.1,isodate==0.6.0,Jinja2==2.11.2,jmespath==0.10.0,jsonpatch==1.28,jsonpointer==2.0,jsonschema==3.2.0,knack==0.7.2,MarkupSafe==1.1.1,msal==1.0.0,msal-extensions==0.1.3,msrest==0.6.19,msrestazure==0.6.4,oauthlib==3.1.0,oci==2.25.1,packaging==20.7,paramiko==2.7.2,pkginfo==1.6.1,pluggy==0.13.1,portalocker==1.7.1,protobuf==3.14.0,py==1.9.0,pyasn1==0.4.8,pyasn1-modules==0.2.8,pycloudlib @ git+https://github.com/canonical/pycloudlib.git@324763289c9a38fc9ac7ec524acb9eb11c7d6c13,pycparser==2.20,Pygments==2.7.3,PyJWT==1.7.1,PyNaCl==1.4.0,pyOpenSSL==19.1.0,pyparsing==2.4.7,pyrsistent==0.17.3,pytest==6.1.2,pytest-cov==2.10.1,python-dateutil==2.8.1,python-simplestreams @ git+https://git.launchpad.net/simplestreams@21c5bba2a5413c51e6b9131fc450e96f6b46090d,pytz==2020.4,PyYAML==5.3.1,requests==2.25.0,requests-oauthlib==1.3.0,rsa==4.6,s3transfer==0.3.3,six==1.15.0,tabulate==0.8.7,toml==0.10.2,uritemplate==3.0.1,urllib3==1.26.2
focal run-test-pre: PYTHONHASHSEED='2445371037'
focal run-test: commands[0] | /tmp/integration-tests-tox/focal/bin/python -m pytest --log-cli-level=INFO bugs/test_lp1898997.py
======================================= test session starts ========================================
platform linux -- Python 3.8.6, pytest-6.1.2, py-1.9.0, pluggy-0.13.1
cachedir: /tmp/integration-tests-tox/focal/.pytest_cache
rootdir: /home/daniel/dev/cloud-init, configfile: tox.ini
plugins: cov-2.10.1
collected 1 item

bugs/test_lp1898997.py::TestInterfaceListingWithOpenvSwitch::test_ovs_member_interfaces_not_excluded
------------------------------------------ live log setup ------------------------------------------
2020-12-10 17:09:56 INFO      integration_testing:clouds.py:73 Detected image: image_id=focal os=ubuntu release=focal
2020-12-10 17:09:56 INFO      integration_testing:clouds.py:73 Detected image: image_id=focal os=ubuntu release=focal
2020-12-10 17:10:07 INFO      integration_testing:clouds.py:104 Settings:
CLOUD_INIT_SOURCE=PROPOSED
COLLECT_LOGS=ON_ERROR
EXISTING_INSTANCE_ID=None
GCE_PROJECT=ubuntu-oddbloke
GCE_REGION=us-central1
GCE_ZONE=a
INSTANCE_TYPE=None
KEEP_IMAGE=False
KEEP_INSTANCE=False
LOCAL_LOG_PATH=/tmp/cloud_init_test_logs
OCI_COMPARTMENT_ID=None
OS_IMAGE=focal
PLATFORM=lxd_vm
RUN_UNSTABLE=False
2020-12-10 17:10:07 INFO      integration_testing:conftest.py:140 Setting up environment for lxd_vm
2020-12-10 17:10:07 INFO      integration_testing:clouds.py:150 Launching instance with launch_kwargs:
image_id=ubuntu:324a6f70e0af79c7d10006de001a7f4e551db8ff4cf42d27da27b845c04da926
user_data=None
wait=False
2020-12-10 17:11:23 INFO      pycloudlib.instance:instance.py:166 executing: sh -c whoami
2020-12-10 17:11:25 INFO      pycloudlib.instance:instance.py:166 executing: sh -c whoami
2020-12-10 17:11:37 INFO      pycloudlib.instance:instance.py:166 executing: sh -c whoami
2020-12-10 17:11:49 INFO      pycloudlib.instance:instance.py:166 executing: sh -c whoami
2020-12-10 17:11:51 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'cloud-init status --help'
2020-12-10 17:11:54 INFO      pycloudlib.instance:instance.py:166 executing: cloud-init status --wait --long
2020-12-10 17:12:07 INFO      integration_testing:clouds.py:159 Launched instance: LXDInstance(name=heroic-termite)
2020-12-10 17:12:07 INFO      integration_testing:instances.py:144 Installing proposed image
2020-12-10 17:12:07 INFO      pycloudlib.instance:instance.py:166 executing: sudo -- sh -c 'echo deb "http://archive.ubuntu.com/ubuntu $(lsb_release -sc)-proposed main" | tee /etc/apt/sources.list.d/proposed.list
apt-get update -q
apt-get install -qy cloud-init'
2020-12-10 17:12:24 INFO      pycloudlib.instance:instance.py:166 executing: sudo -- sh -c 'cloud-init -v'
2020-12-10 17:12:25 INFO      integration_testing:instances.py:137 Installed cloud-init version: 20.4-0ubuntu1~20.04.1
2020-12-10 17:12:25 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'sudo cloud-init clean --logs'
2020-12-10 17:12:27 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'sudo rm -rf /var/log/syslog'
2020-12-10 17:12:27 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'sudo cloud-init clean --logs'
2020-12-10 17:12:28 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'sudo rm -rf /var/log/syslog'
2020-12-10 17:12:29 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'sudo cloud-init clean --logs'
2020-12-10 17:12:30 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'sudo rm -rf /var/log/syslog'
2020-12-10 17:14:02 INFO      integration_testing:instances.py:117 Created new image: local:heroic-termite-snapshot
2020-12-10 17:14:02 INFO      integration_testing:conftest.py:146 Done with environment setup
2020-12-10 17:14:02 INFO      integration_testing:clouds.py:150 Launching instance with launch_kwargs:
image_id=local:heroic-termite-snapshot
user_data=None
wait=False
config_dict={'user.network-config': 'bridges:\n        ovs-br:\n            dhcp4: true\n            interfaces:\n            - enp5s0\n            macaddress: 52:54:00:d9:08:1c\n            mtu: 1500\n            openvswitch: {}\nethernets:\n    enp5s0:\n      mtu: 1500\n      set-name: enp5s0\n      match:\n          macaddress: de:ad:be:ef:12:34\nversion: 2\n', 'volatile.eth0.hwaddr': 'de:ad:be:ef:12:34'}
2020-12-10 17:15:51 INFO      pycloudlib.instance:instance.py:166 executing: sh -c whoami
2020-12-10 17:15:53 INFO      pycloudlib.instance:instance.py:166 executing: sh -c whoami
2020-12-10 17:16:05 INFO      pycloudlib.instance:instance.py:166 executing: sh -c whoami
2020-12-10 17:16:17 INFO      pycloudlib.instance:instance.py:166 executing: sh -c whoami
2020-12-10 17:16:18 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'cloud-init status --help'
2020-12-10 17:16:19 INFO      pycloudlib.instance:instance.py:166 executing: cloud-init status --wait --long
2020-12-10 17:16:20 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'cloud-init status --help'
2020-12-10 17:16:22 INFO      pycloudlib.instance:instance.py:166 executing: cloud-init status --wait --long
2020-12-10 17:16:23 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'cloud-init status --help'
2020-12-10 17:16:24 INFO      pycloudlib.instance:instance.py:166 executing: cloud-init status --wait --long
2020-12-10 17:16:25 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'cloud-init status --help'
2020-12-10 17:16:26 INFO      pycloudlib.instance:instance.py:166 executing: cloud-init status --wait --long
2020-12-10 17:16:27 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'cloud-init status --help'
2020-12-10 17:16:28 INFO      pycloudlib.instance:instance.py:166 executing: cloud-init status --wait --long
2020-12-10 17:16:29 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'cloud-init status --help'
2020-12-10 17:16:30 INFO      pycloudlib.instance:instance.py:166 executing: cloud-init status --wait --long
2020-12-10 17:16:31 INFO      integration_testing:clouds.py:159 Launched instance: LXDInstance(name=flying-blowfish)
------------------------------------------ live log call -------------------------------------------
2020-12-10 17:16:31 INFO      pycloudlib.instance:instance.py:166 executing: sudo -- sh -c 'dhclient enp5s0'
2020-12-10 17:16:32 INFO      pycloudlib.instance:instance.py:166 executing: sudo -- sh -c 'apt update -qqy'
2020-12-10 17:16:38 INFO      pycloudlib.instance:instance.py:166 executing: sudo -- sh -c 'apt-get install -qqy openvswitch-switch'
2020-12-10 17:16:48 INFO      pycloudlib.instance:instance.py:166 executing: sudo -- sh -c 'cloud-init clean --logs'
2020-12-10 17:16:51 INFO      integration_testing:instances.py:67 Instance restarted; waiting for boot
2020-12-10 17:16:51 INFO      pycloudlib.instance:instance.py:166 executing: sh -c whoami
2020-12-10 17:16:54 INFO      pycloudlib.instance:instance.py:166 executing: sh -c whoami
2020-12-10 17:17:06 INFO      pycloudlib.instance:instance.py:166 executing: sh -c whoami
2020-12-10 17:17:08 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'cloud-init status --help'
2020-12-10 17:17:09 INFO      pycloudlib.instance:instance.py:166 executing: cloud-init status --wait --long
2020-12-10 17:17:11 INFO      pycloudlib.instance:instance.py:166 executing: sudo -- sh -c 'cat /var/log/cloud-init.log'
2020-12-10 17:17:11 INFO      pycloudlib.instance:instance.py:166 executing: sudo -- sh -c 'ip addr'
2020-12-10 17:17:12 INFO      pycloudlib.instance:instance.py:166 executing: sudo -- sh -c 'ip -4 route show default | awk '"'"'{ print $3 }'"'"''
2020-12-10 17:17:13 INFO      pycloudlib.instance:instance.py:166 executing: sudo -- sh -c 'ping -c 1 -W 1 -I ovs-br 10.236.135.1'
PASSED                                                                                       [100%]
---------------------------------------- live log teardown -----------------------------------------
2020-12-10 17:17:15 INFO      integration_testing:clouds.py:178 Deleting snapshot image created for this testrun: local:heroic-termite-snapshot


========================================= warnings summary =========================================
tests/integration_tests/bugs/test_lp1898997.py::TestInterfaceListingWithOpenvSwitch::test_ovs_member_interfaces_not_excluded
tests/integration_tests/bugs/test_lp1898997.py::TestInterfaceListingWithOpenvSwitch::test_ovs_member_interfaces_not_excluded
  /tmp/integration-tests-tox/focal/lib/python3.8/site-packages/simplestreams/mirrors/__init__.py:206: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
    LOG.warn("got ENOENT for (%s, %s), trying with trailing /",

-- Docs: https://docs.pytest.org/en/stable/warnings.html
============================ 1 passed, 2 warnings in 438.76s (0:07:18) =============================
```

groovy:

======================================= test session starts ========================================
platform linux -- Python 3.8.6, pytest-6.1.0, py-1.9.0, pluggy-0.13.1
rootdir: /home/daniel/dev/cloud-init, configfile: tox.ini
plugins: xdist-2.1.0, forked-1.3.0, parallel-0.1.0, cov-2.8.1
collected 1 item

tests/integration_tests/bugs/test_lp1898997.py::TestInterfaceListingWithOpenvSwitch::test_ovs_member_interfaces_not_excluded
------------------------------------------ live log setup ------------------------------------------
2020-12-10 17:22:33 INFO      integration_testing:clouds.py:73 Detected image: image_id=groovy os=ubuntu release=groovy
2020-12-10 17:22:33 INFO      integration_testing:clouds.py:73 Detected image: image_id=groovy os=ubuntu release=groovy
2020-12-10 17:22:43 INFO      integration_testing:clouds.py:104 Settings:
CLOUD_INIT_SOURCE=PROPOSED
COLLECT_LOGS=ON_ERROR
EXISTING_INSTANCE_ID=None
GCE_PROJECT=ubuntu-oddbloke
GCE_REGION=us-central1
GCE_ZONE=a
INSTANCE_TYPE=None
KEEP_IMAGE=true
KEEP_INSTANCE=False
LOCAL_LOG_PATH=/tmp/cloud_init_test_logs
OCI_COMPARTMENT_ID=None
OS_IMAGE=groovy
PLATFORM=lxd_vm
RUN_UNSTABLE=False
2020-12-10 17:22:43 INFO      integration_testing:conftest.py:140 Setting up environment for lxd_vm
2020-12-10 17:22:43 INFO      integration_testing:clouds.py:150 Launching instance with launch_kwargs:
image_id=ubuntu:ed0f5fac022e75c2dd6453c4a702da3abf60cb9dee19af0a30123e2f42c5d9cf
user_data=None
wait=False
2020-12-10 17:24:56 INFO      pycloudlib.instance:instance.py:166 executing: sh -c whoami
2020-12-10 17:24:58 INFO      pycloudlib.instance:instance.py:166 executing: sh -c whoami
2020-12-10 17:25:11 INFO      pycloudlib.instance:instance.py:166 executing: sh -c whoami
2020-12-10 17:25:23 INFO      pycloudlib.instance:instance.py:166 executing: sh -c whoami
2020-12-10 17:25:25 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'cloud-init status --help'
2020-12-10 17:25:27 INFO      pycloudlib.instance:instance.py:166 executing: cloud-init status --wait --long
2020-12-10 17:25:33 INFO      integration_testing:clouds.py:159 Launched instance: LXDInstance(name=still-monkey)
2020-12-10 17:25:33 INFO      integration_testing:instances.py:144 Installing proposed image
2020-12-10 17:25:33 INFO      pycloudlib.instance:instance.py:166 executing: sudo -- sh -c 'echo deb "http://archive.ubuntu.com/ubuntu $(lsb_release -sc)-proposed main" | tee /etc/apt/sources.list.d/proposed.list
apt-get update -q
apt-get install -qy cloud-init'
2020-12-10 17:25:50 INFO      pycloudlib.instance:instance.py:166 executing: sudo -- sh -c 'cloud-init -v'
2020-12-10 17:25:51 INFO      integration_testing:instances.py:137 Installed cloud-init version: 20.4-0ubuntu1~20.10.1
2020-12-10 17:25:51 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'sudo cloud-init clean --logs'
2020-12-10 17:25:52 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'sudo rm -rf /var/log/syslog'
2020-12-10 17:25:53 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'sudo cloud-init clean --logs'
2020-12-10 17:25:54 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'sudo rm -rf /var/log/syslog'
2020-12-10 17:25:55 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'sudo cloud-init clean --logs'
2020-12-10 17:25:56 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'sudo rm -rf /var/log/syslog'
2020-12-10 17:27:26 INFO      integration_testing:instances.py:117 Created new image: local:still-monkey-snapshot
2020-12-10 17:27:27 INFO      integration_testing:conftest.py:146 Done with environment setup
2020-12-10 17:27:27 INFO      integration_testing:clouds.py:150 Launching instance with launch_kwargs:
image_id=local:still-monkey-snapshot
user_data=None
wait=False
config_dict={'user.network-config': 'bridges:\n        ovs-br:\n            dhcp4: true\n            interfaces:\n            - enp5s0\n            macaddress: 52:54:00:d9:08:1c\n            mtu: 1500\n            openvswitch: {}\nethernets:\n    enp5s0:\n      mtu: 1500\n      set-name: enp5s0\n      match:\n          macaddress: de:ad:be:ef:12:34\nversion: 2\n', 'volatile.eth0.hwaddr': 'de:ad:be:ef:12:34'}
2020-12-10 17:28:59 INFO      pycloudlib.instance:instance.py:166 executing: sh -c whoami
2020-12-10 17:29:01 INFO      pycloudlib.instance:instance.py:166 executing: sh -c whoami
2020-12-10 17:29:13 INFO      pycloudlib.instance:instance.py:166 executing: sh -c whoami
2020-12-10 17:29:25 INFO      pycloudlib.instance:instance.py:166 executing: sh -c whoami
2020-12-10 17:29:27 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'cloud-init status --help'
2020-12-10 17:29:28 INFO      pycloudlib.instance:instance.py:166 executing: cloud-init status --wait --long
2020-12-10 17:29:30 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'cloud-init status --help'
2020-12-10 17:29:31 INFO      pycloudlib.instance:instance.py:166 executing: cloud-init status --wait --long
2020-12-10 17:29:32 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'cloud-init status --help'
2020-12-10 17:29:33 INFO      pycloudlib.instance:instance.py:166 executing: cloud-init status --wait --long
2020-12-10 17:29:34 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'cloud-init status --help'
2020-12-10 17:29:35 INFO      pycloudlib.instance:instance.py:166 executing: cloud-init status --wait --long
2020-12-10 17:29:36 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'cloud-init status --help'
2020-12-10 17:29:37 INFO      pycloudlib.instance:instance.py:166 executing: cloud-init status --wait --long
2020-12-10 17:29:38 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'cloud-init status --help'
2020-12-10 17:29:39 INFO      pycloudlib.instance:instance.py:166 executing: cloud-init status --wait --long
2020-12-10 17:29:40 INFO      integration_testing:clouds.py:159 Launched instance: LXDInstance(name=pro-dane)
------------------------------------------ live log call -------------------------------------------
2020-12-10 17:29:40 INFO      pycloudlib.instance:instance.py:166 executing: sudo -- sh -c 'dhclient enp5s0'
2020-12-10 17:29:41 INFO      pycloudlib.instance:instance.py:166 executing: sudo -- sh -c 'apt update -qqy'
2020-12-10 17:29:46 INFO      pycloudlib.instance:instance.py:166 executing: sudo -- sh -c 'apt-get install -qqy openvswitch-switch'
2020-12-10 17:29:54 INFO      pycloudlib.instance:instance.py:166 executing: sudo -- sh -c 'cloud-init clean --logs'
2020-12-10 17:29:58 INFO      integration_testing:instances.py:67 Instance restarted; waiting for boot
2020-12-10 17:29:58 INFO      pycloudlib.instance:instance.py:166 executing: sh -c whoami
2020-12-10 17:30:00 INFO      pycloudlib.instance:instance.py:166 executing: sh -c whoami
2020-12-10 17:30:12 INFO      pycloudlib.instance:instance.py:166 executing: sh -c whoami
2020-12-10 17:30:14 INFO      pycloudlib.instance:instance.py:166 executing: sh -c 'cloud-init status --help'
2020-12-10 17:30:17 INFO      pycloudlib.instance:instance.py:166 executing: cloud-init status --wait --long
2020-12-10 17:30:19 INFO      pycloudlib.instance:instance.py:166 executing: sudo -- sh -c 'cat /var/log/cloud-init.log'
2020-12-10 17:30:20 INFO      pycloudlib.instance:instance.py:166 executing: sudo -- sh -c 'ip addr'
2020-12-10 17:30:20 INFO      pycloudlib.instance:instance.py:166 executing: sudo -- sh -c 'ip -4 route show default | awk '"'"'{ print $3 }'"'"''
2020-12-10 17:30:21 INFO      pycloudlib.instance:instance.py:166 executing: sudo -- sh -c 'ping -c 1 -W 1 -I ovs-br 10.236.135.1'
PASSED                                                                                       [100%]
---------------------------------------- live log teardown -----------------------------------------
2020-12-10 17:30:23 INFO      integration_testing:clouds.py:174 NOT deleting snapshot image created for this testrun because KEEP_IMAGE is True: local:still-monkey-snapshot


========================================= warnings summary =========================================
tests/integration_tests/bugs/test_lp1898997.py::TestInterfaceListingWithOpenvSwitch::test_ovs_member_interfaces_not_excluded
tests/integration_tests/bugs/test_lp1898997.py::TestInterfaceListingWithOpenvSwitch::test_ovs_member_interfaces_not_excluded
  /home/daniel/.virtualenvs/cloud-init/lib/python3.8/site-packages/simplestreams/mirrors/__init__.py:206: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
    LOG.warn("got ENOENT for (%s, %s), trying with trailing /",

-- Docs: https://docs.pytest.org/en/stable/warnings.html
============================ 1 passed, 2 warnings in 470.19s (0:07:50) =============================

[Regression Potential]

This change modifies how cloud-init determines the physical interfaces present
in a system.  This could affect any cloud-init instance that applies network
configuration (which is most of them), if there is an issue.  (We would likely
see broad failures if there were an issue, however.)
